
# AGENT
GAMETE_FITNESS_STD = 5
PROPORTION_GIVING_AS_INHERITANCE = 0.5
AVERAGE_ASSET_LIFESPAN = 40
AVERAGE_ASSET_RETURN = 0.05
CAREER_SUCCESS_CONSTANT = 1000
CAREER_SUCCESS_EXPONENTIAL = 1.05
DEFAULT_FITNESS_MEAN = 50
DEFAULT_FITNESS_STD = 5


# GENERATION
GENERATION_SIZE = 10
ENVIRONMENTAL_RANDOMNESS_RANGE = 20


