
# AGENT
GAMETE_FITNESS_STD = 5
PROPORTION_GIVING_AS_INHERITANCE = 0.5
AVERAGE_ASSET_LIFESPAN = 40
AVERAGE_ASSET_RETURN = 0.00
CAREER_SUCCESS_CONSTANT = 100
CAREER_SUCCESS_EXPONENTIAL = 1.05
DEFAULT_FITNESS_MEAN = 50
DEFAULT_FITNESS_STD = 5
DEFAULT_INHERITANCE_MEAN = 100
DEFAULT_INHERITANCE_STD = 10


# GENERATION
GENERATION_SIZE = 4000
ENVIRONMENTAL_RANDOMNESS_RANGE = 20


# SIMULATOR
NUM_GENERATIONS = 10

